In [ ]:
import pandas as pd
import numpy as np
from numpy.random import default_rng
rng = default_rng(12345)
three = rng.uniform(-0.2, 1.0, size=100)
three[three < 0] = np.nan

In [ ]:
data_frame = pd.DataFrame({
    "one": rng.random(size=100),
    "two": rng.normal(0, 1, size=100).cumsum(),
    "three": three
})

In [ ]:
data_frame["four"] = data_frame["one"] > 0.5

In [ ]:
def transform_function(row):
    if row["four"]:
        return 0.5*row["two"]
    return row["one"]*row["two"]

In [ ]:
data_frame["five"] = data_frame.apply(transform_function, axis=1)

In [ ]:
print(data_frame)

In [ ]:
df = data_frame.dropna()

In [ ]:
print(df)